name: pymob

on:
  workflow_dispatch:

jobs:
  pymob:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: curl -LOC- https://www.python.org/ftp/python/3.13.7/python-3.13.7-embed-amd64.zip

      - run: unzip python-*.zip

      - run: ls python*
      
      - run: sed -i -e "s/#import site/import site/" python*._pth

      - run: cat python*._pth
        shell: bash

      - run: curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py

      - run: .\python.exe get-pip.py

      - run: .\python.exe .\Scripts\pip.exe install setuptools wheel

      - run: .\python.exe .\Scripts\pip.exe install pymobiledevice3

      - run: tar -cf - . | zstd -T0 -9 > pymob.tar.zst

      - run: gh release create pymob pymob.tar.zst
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
