name: pymob

on:
  workflow_dispatch:

jobs:
  pymob:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: winget install --id=Python.Python.3.13  -e --accept-package-agreements --accept-source-agreements

      - run: |
          python -m venv pymob
          .\pymob\Scripts\activate
          pip install -U setuptools wheel gpxpy pymobiledevice3

      - run: tar -cf - . | zstd -T0 -9 > pymob.tar.zst

      - run: gh release create pymob pymob.tar.zst
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
